### ISSUE TITLE
Add required progs in README

### ISSUE THREAD

**Issue by archiewood** [ziodotsh/atfile#10]
```
~$ atfile upload tools.csv
Error: 'md5sum' not installed
```

Perhaps list this as a prerequisite?

**Comment by electricduck** [comment]
> ```
> ~$ atfile upload tools.csv
> Error: 'md5sum' not installed
> ```
> 
> Perhaps list this as a prerequisite?

There's a few progs dotted around that it needs, as well as some optional ones (which trigger when required). But I guess there's no harm in sticking it in the README :+1:

**Comment by electricduck** [comment]
@archiewood Added requirements to the README: https://github.com/ziodotsh/atfile?tab=readme-ov-file#-requirements
